server:
  port: 8061

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER:localhost}:8761/eureka


spring:
#  config:#    import: "optional:configserver:"  cloud:
#    discovery:#      enabled: true
    config:
      uri:
      - http://${CONFIG_SERVER:localhost}:8888/
    gateway:
 #     discovery: #       locator: #         enabled: true
 #         lower-case-service-id: true  
      routes:
        - id: theaters
          uri: lb://THEATER-SERVICE
          predicates:
            - Path=/theaters/**

logging:
  level:
    com:
      logixal: error

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always