server:
  port: 8061

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER:localhost}:8761/eureka


spring:
  cloud:
    config:
      uri:
      - http://${CONFIG_SERVER:localhost}:8888/
    gateway:
      routes:
        - id: theaters
          uri: lb://THEATER-SERVICE
          predicates:
            - Path=/theaters/**
        - id: user
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
        - id: booking
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/booking/**
        - id: payment
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**

logging:
  level:
    com:
      logixal: info

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always