server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sysachinp/atgms-git-config.git
          clone-on-start: true
          username: desadmin@prassy.com
          password: 12345
          default-label: config-test