server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sysachinp/atgms-git-config.git
          clone-on-start: true
          username: desadmin@logixal.com
          password: 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
          #password: 12345
          default-label: config-test